<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/trunks.proto

namespace Fonoster\Routr\Connect\Trunks\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The message for the Trunk.FindBy
 *
 * Generated from protobuf message <code>fonoster.routr.connect.trunks.v2beta1.FindByRequest</code>
 */
class FindByRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The field name to search
     *
     * Generated from protobuf field <code>string field_name = 1 [json_name = "fieldName"];</code>
     */
    protected $field_name = '';
    /**
     * The value to search
     *
     * Generated from protobuf field <code>string field_value = 2 [json_name = "fieldValue"];</code>
     */
    protected $field_value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field_name
     *           The field name to search
     *     @type string $field_value
     *           The value to search
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Trunks::initOnce();
        parent::__construct($data);
    }

    /**
     * The field name to search
     *
     * Generated from protobuf field <code>string field_name = 1 [json_name = "fieldName"];</code>
     *
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * The field name to search
     *
     * Generated from protobuf field <code>string field_name = 1 [json_name = "fieldName"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, true);
        $this->field_name = $var;

        return $this;
    }

    /**
     * The value to search
     *
     * Generated from protobuf field <code>string field_value = 2 [json_name = "fieldValue"];</code>
     *
     * @return string
     */
    public function getFieldValue()
    {
        return $this->field_value;
    }

    /**
     * The value to search
     *
     * Generated from protobuf field <code>string field_value = 2 [json_name = "fieldValue"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setFieldValue($var)
    {
        GPBUtil::checkString($var, true);
        $this->field_value = $var;

        return $this;
    }
}
