<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/trunks.proto

namespace Fonoster\Routr\Connect\Trunks\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The message for the Trunk resource
 *
 * Generated from protobuf message <code>fonoster.routr.connect.trunks.v2beta1.Trunk</code>
 */
class Trunk extends \Google\Protobuf\Internal\Message
{
    /**
     * The API version of the Trunk
     *
     * Generated from protobuf field <code>string api_version = 2 [json_name = "apiVersion"];</code>
     */
    protected $api_version = '';
    /**
     * The reference of the Trunk
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     */
    protected $ref = '';
    /**
     * The name of the Trunk
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * A flag to indicate if we should send a REGISTER request to the Trunk
     *
     * Generated from protobuf field <code>bool send_register = 4 [json_name = "sendRegister"];</code>
     */
    protected $send_register = false;
    /**
     * The URI for inbound requests
     *
     * Generated from protobuf field <code>string inbound_uri = 5 [json_name = "inboundUri"];</code>
     */
    protected $inbound_uri = '';
    /**
     * The date and time when the Trunk was created
     *
     * Generated from protobuf field <code>int32 created_at = 6 [json_name = "createdAt"];</code>
     */
    protected $created_at = 0;
    /**
     * The date and time when the Trunk was last updated
     *
     * Generated from protobuf field <code>int32 updated_at = 7 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = 0;
    /**
     * The list of IP addresses that are allowed to access the Trunks
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.acl.v2beta1.AccessControlList access_control_list = 8 [json_name = "accessControlList"];</code>
     */
    protected $access_control_list = null;
    /**
     * The credentials to use when authenticating with the Trunk
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.credentials.v2beta1.Credentials inbound_credentials = 9 [json_name = "inboundCredentials"];</code>
     */
    protected $inbound_credentials = null;
    /**
     * The credentials to use when authenticating with the Provider
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.credentials.v2beta1.Credentials outbound_credentials = 10 [json_name = "outboundCredentials"];</code>
     */
    protected $outbound_credentials = null;
    /**
     * The list of URIs for the Trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.trunks.v2beta1.TrunkURI uris = 11 [json_name = "uris"];</code>
     */
    private $uris;
    /**
     * The extended attributes of the Trunk
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 12 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_version
     *           The API version of the Trunk
     *     @type string $ref
     *           The reference of the Trunk
     *     @type string $name
     *           The name of the Trunk
     *     @type bool $send_register
     *           A flag to indicate if we should send a REGISTER request to the Trunk
     *     @type string $inbound_uri
     *           The URI for inbound requests
     *     @type int $created_at
     *           The date and time when the Trunk was created
     *     @type int $updated_at
     *           The date and time when the Trunk was last updated
     *     @type \Fonoster\Routr\Connect\Acl\V2beta1\AccessControlList $access_control_list
     *           The list of IP addresses that are allowed to access the Trunks
     *     @type \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials $inbound_credentials
     *           The credentials to use when authenticating with the Trunk
     *     @type \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials $outbound_credentials
     *           The credentials to use when authenticating with the Provider
     *     @type array<\Fonoster\Routr\Connect\Trunks\V2beta1\TrunkURI>|\Google\Protobuf\Internal\RepeatedField $uris
     *           The list of URIs for the Trunk
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the Trunk
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Trunks::initOnce();
        parent::__construct($data);
    }

    /**
     * The API version of the Trunk
     *
     * Generated from protobuf field <code>string api_version = 2 [json_name = "apiVersion"];</code>
     *
     * @return string
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * The API version of the Trunk
     *
     * Generated from protobuf field <code>string api_version = 2 [json_name = "apiVersion"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setApiVersion($var)
    {
        GPBUtil::checkString($var, true);
        $this->api_version = $var;

        return $this;
    }

    /**
     * The reference of the Trunk
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The reference of the Trunk
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * The name of the Trunk
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Trunk
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * A flag to indicate if we should send a REGISTER request to the Trunk
     *
     * Generated from protobuf field <code>bool send_register = 4 [json_name = "sendRegister"];</code>
     *
     * @return boolean
     */
    public function getSendRegister()
    {
        return $this->send_register;
    }

    /**
     * A flag to indicate if we should send a REGISTER request to the Trunk
     *
     * Generated from protobuf field <code>bool send_register = 4 [json_name = "sendRegister"];</code>
     *
     * @param  boolean $var
     * @return $this
     */
    public function setSendRegister($var)
    {
        GPBUtil::checkBool($var);
        $this->send_register = $var;

        return $this;
    }

    /**
     * The URI for inbound requests
     *
     * Generated from protobuf field <code>string inbound_uri = 5 [json_name = "inboundUri"];</code>
     *
     * @return string
     */
    public function getInboundUri()
    {
        return $this->inbound_uri;
    }

    /**
     * The URI for inbound requests
     *
     * Generated from protobuf field <code>string inbound_uri = 5 [json_name = "inboundUri"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setInboundUri($var)
    {
        GPBUtil::checkString($var, true);
        $this->inbound_uri = $var;

        return $this;
    }

    /**
     * The date and time when the Trunk was created
     *
     * Generated from protobuf field <code>int32 created_at = 6 [json_name = "createdAt"];</code>
     *
     * @return integer
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * The date and time when the Trunk was created
     *
     * Generated from protobuf field <code>int32 created_at = 6 [json_name = "createdAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * The date and time when the Trunk was last updated
     *
     * Generated from protobuf field <code>int32 updated_at = 7 [json_name = "updatedAt"];</code>
     *
     * @return integer
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * The date and time when the Trunk was last updated
     *
     * Generated from protobuf field <code>int32 updated_at = 7 [json_name = "updatedAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * The list of IP addresses that are allowed to access the Trunks
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.acl.v2beta1.AccessControlList access_control_list = 8 [json_name = "accessControlList"];</code>
     *
     * @return \Fonoster\Routr\Connect\Acl\V2beta1\AccessControlList|null
     */
    public function getAccessControlList()
    {
        return $this->access_control_list;
    }

    public function hasAccessControlList()
    {
        return isset($this->access_control_list);
    }

    public function clearAccessControlList()
    {
        unset($this->access_control_list);
    }

    /**
     * The list of IP addresses that are allowed to access the Trunks
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.acl.v2beta1.AccessControlList access_control_list = 8 [json_name = "accessControlList"];</code>
     *
     * @param  \Fonoster\Routr\Connect\Acl\V2beta1\AccessControlList $var
     * @return $this
     */
    public function setAccessControlList($var)
    {
        GPBUtil::checkMessage($var, \Fonoster\Routr\Connect\Acl\V2beta1\AccessControlList::class);
        $this->access_control_list = $var;

        return $this;
    }

    /**
     * The credentials to use when authenticating with the Trunk
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.credentials.v2beta1.Credentials inbound_credentials = 9 [json_name = "inboundCredentials"];</code>
     *
     * @return \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials|null
     */
    public function getInboundCredentials()
    {
        return $this->inbound_credentials;
    }

    public function hasInboundCredentials()
    {
        return isset($this->inbound_credentials);
    }

    public function clearInboundCredentials()
    {
        unset($this->inbound_credentials);
    }

    /**
     * The credentials to use when authenticating with the Trunk
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.credentials.v2beta1.Credentials inbound_credentials = 9 [json_name = "inboundCredentials"];</code>
     *
     * @param  \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials $var
     * @return $this
     */
    public function setInboundCredentials($var)
    {
        GPBUtil::checkMessage($var, \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials::class);
        $this->inbound_credentials = $var;

        return $this;
    }

    /**
     * The credentials to use when authenticating with the Provider
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.credentials.v2beta1.Credentials outbound_credentials = 10 [json_name = "outboundCredentials"];</code>
     *
     * @return \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials|null
     */
    public function getOutboundCredentials()
    {
        return $this->outbound_credentials;
    }

    public function hasOutboundCredentials()
    {
        return isset($this->outbound_credentials);
    }

    public function clearOutboundCredentials()
    {
        unset($this->outbound_credentials);
    }

    /**
     * The credentials to use when authenticating with the Provider
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.credentials.v2beta1.Credentials outbound_credentials = 10 [json_name = "outboundCredentials"];</code>
     *
     * @param  \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials $var
     * @return $this
     */
    public function setOutboundCredentials($var)
    {
        GPBUtil::checkMessage($var, \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials::class);
        $this->outbound_credentials = $var;

        return $this;
    }

    /**
     * The list of URIs for the Trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.trunks.v2beta1.TrunkURI uris = 11 [json_name = "uris"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUris()
    {
        return $this->uris;
    }

    /**
     * The list of URIs for the Trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.trunks.v2beta1.TrunkURI uris = 11 [json_name = "uris"];</code>
     *
     * @param  array<\Fonoster\Routr\Connect\Trunks\V2beta1\TrunkURI>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUris($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fonoster\Routr\Connect\Trunks\V2beta1\TrunkURI::class);
        $this->uris = $arr;

        return $this;
    }

    /**
     * The extended attributes of the Trunk
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 12 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the Trunk
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 12 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
