<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/trunks.proto

namespace Fonoster\Routr\Connect\Trunks\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The message for the Trunk URIs
 *
 * Generated from protobuf message <code>fonoster.routr.connect.trunks.v2beta1.TrunkURI</code>
 */
class TrunkURI extends \Google\Protobuf\Internal\Message
{
    /**
     * The host name or IP address of the Trunk
     *
     * Generated from protobuf field <code>string host = 1 [json_name = "host"];</code>
     */
    protected $host = '';
    /**
     * The port number of the Trunk
     *
     * Generated from protobuf field <code>int32 port = 2 [json_name = "port"];</code>
     */
    protected $port = 0;
    /**
     * The transport protocol of the Trunk
     *
     * Generated from protobuf field <code>string transport = 3 [json_name = "transport"];</code>
     */
    protected $transport = '';
    /**
     * The username to use when authenticating with the Trunk
     *
     * Generated from protobuf field <code>string user = 4 [json_name = "user"];</code>
     */
    protected $user = '';
    /**
     * The weight of the Trunk
     *
     * Generated from protobuf field <code>int32 weight = 5 [json_name = "weight"];</code>
     */
    protected $weight = 0;
    /**
     * The priority of the Trunk
     *
     * Generated from protobuf field <code>int32 priority = 6 [json_name = "priority"];</code>
     */
    protected $priority = 0;
    /**
     * The flag to enable or disable the Trunk
     *
     * Generated from protobuf field <code>bool enabled = 7 [json_name = "enabled"];</code>
     */
    protected $enabled = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $host
     *           The host name or IP address of the Trunk
     *     @type int $port
     *           The port number of the Trunk
     *     @type string $transport
     *           The transport protocol of the Trunk
     *     @type string $user
     *           The username to use when authenticating with the Trunk
     *     @type int $weight
     *           The weight of the Trunk
     *     @type int $priority
     *           The priority of the Trunk
     *     @type bool $enabled
     *           The flag to enable or disable the Trunk
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Trunks::initOnce();
        parent::__construct($data);
    }

    /**
     * The host name or IP address of the Trunk
     *
     * Generated from protobuf field <code>string host = 1 [json_name = "host"];</code>
     *
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * The host name or IP address of the Trunk
     *
     * Generated from protobuf field <code>string host = 1 [json_name = "host"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, true);
        $this->host = $var;

        return $this;
    }

    /**
     * The port number of the Trunk
     *
     * Generated from protobuf field <code>int32 port = 2 [json_name = "port"];</code>
     *
     * @return integer
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * The port number of the Trunk
     *
     * Generated from protobuf field <code>int32 port = 2 [json_name = "port"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * The transport protocol of the Trunk
     *
     * Generated from protobuf field <code>string transport = 3 [json_name = "transport"];</code>
     *
     * @return string
     */
    public function getTransport()
    {
        return $this->transport;
    }

    /**
     * The transport protocol of the Trunk
     *
     * Generated from protobuf field <code>string transport = 3 [json_name = "transport"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setTransport($var)
    {
        GPBUtil::checkString($var, true);
        $this->transport = $var;

        return $this;
    }

    /**
     * The username to use when authenticating with the Trunk
     *
     * Generated from protobuf field <code>string user = 4 [json_name = "user"];</code>
     *
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * The username to use when authenticating with the Trunk
     *
     * Generated from protobuf field <code>string user = 4 [json_name = "user"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, true);
        $this->user = $var;

        return $this;
    }

    /**
     * The weight of the Trunk
     *
     * Generated from protobuf field <code>int32 weight = 5 [json_name = "weight"];</code>
     *
     * @return integer
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * The weight of the Trunk
     *
     * Generated from protobuf field <code>int32 weight = 5 [json_name = "weight"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * The priority of the Trunk
     *
     * Generated from protobuf field <code>int32 priority = 6 [json_name = "priority"];</code>
     *
     * @return integer
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * The priority of the Trunk
     *
     * Generated from protobuf field <code>int32 priority = 6 [json_name = "priority"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkInt32($var);
        $this->priority = $var;

        return $this;
    }

    /**
     * The flag to enable or disable the Trunk
     *
     * Generated from protobuf field <code>bool enabled = 7 [json_name = "enabled"];</code>
     *
     * @return boolean
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * The flag to enable or disable the Trunk
     *
     * Generated from protobuf field <code>bool enabled = 7 [json_name = "enabled"];</code>
     *
     * @param  boolean $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }
}
