<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/trunks.proto

namespace Fonoster\Routr\Connect\Trunks\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The message for the Trunk.Update
 *
 * Generated from protobuf message <code>fonoster.routr.connect.trunks.v2beta1.UpdateTrunkRequest</code>
 */
class UpdateTrunkRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The API version of the Trunk
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     */
    protected $api_version = '';
    /**
     * The reference of the Trunk
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     */
    protected $ref = '';
    /**
     * The name of the Trunk
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * A flag to indicate if we should send a REGISTER request to the Trunk
     *
     * Generated from protobuf field <code>bool send_register = 4 [json_name = "sendRegister"];</code>
     */
    protected $send_register = false;
    /**
     * The URI for inbound requests
     *
     * Generated from protobuf field <code>string inbound_uri = 5 [json_name = "inboundUri"];</code>
     */
    protected $inbound_uri = '';
    /**
     * Reference to the AccessControlList
     *
     * Generated from protobuf field <code>string access_control_list_ref = 6 [json_name = "accessControlListRef"];</code>
     */
    protected $access_control_list_ref = '';
    /**
     * Reference to the inbound Credentials
     *
     * Generated from protobuf field <code>string inbound_credentials_ref = 7 [json_name = "inboundCredentialsRef"];</code>
     */
    protected $inbound_credentials_ref = '';
    /**
     * Reference to the outbound Credentials
     *
     * Generated from protobuf field <code>string outbound_credentials_ref = 8 [json_name = "outboundCredentialsRef"];</code>
     */
    protected $outbound_credentials_ref = '';
    /**
     * The list of URIs for the Trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.trunks.v2beta1.TrunkURI uris = 9 [json_name = "uris"];</code>
     */
    private $uris;
    /**
     * The extended attributes of the Trunk
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 10 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_version
     *           The API version of the Trunk
     *     @type string $ref
     *           The reference of the Trunk
     *     @type string $name
     *           The name of the Trunk
     *     @type bool $send_register
     *           A flag to indicate if we should send a REGISTER request to the Trunk
     *     @type string $inbound_uri
     *           The URI for inbound requests
     *     @type string $access_control_list_ref
     *           Reference to the AccessControlList
     *     @type string $inbound_credentials_ref
     *           Reference to the inbound Credentials
     *     @type string $outbound_credentials_ref
     *           Reference to the outbound Credentials
     *     @type array<\Fonoster\Routr\Connect\Trunks\V2beta1\TrunkURI>|\Google\Protobuf\Internal\RepeatedField $uris
     *           The list of URIs for the Trunk
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the Trunk
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Trunks::initOnce();
        parent::__construct($data);
    }

    /**
     * The API version of the Trunk
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @return string
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * The API version of the Trunk
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setApiVersion($var)
    {
        GPBUtil::checkString($var, true);
        $this->api_version = $var;

        return $this;
    }

    /**
     * The reference of the Trunk
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The reference of the Trunk
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * The name of the Trunk
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Trunk
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * A flag to indicate if we should send a REGISTER request to the Trunk
     *
     * Generated from protobuf field <code>bool send_register = 4 [json_name = "sendRegister"];</code>
     *
     * @return boolean
     */
    public function getSendRegister()
    {
        return $this->send_register;
    }

    /**
     * A flag to indicate if we should send a REGISTER request to the Trunk
     *
     * Generated from protobuf field <code>bool send_register = 4 [json_name = "sendRegister"];</code>
     *
     * @param  boolean $var
     * @return $this
     */
    public function setSendRegister($var)
    {
        GPBUtil::checkBool($var);
        $this->send_register = $var;

        return $this;
    }

    /**
     * The URI for inbound requests
     *
     * Generated from protobuf field <code>string inbound_uri = 5 [json_name = "inboundUri"];</code>
     *
     * @return string
     */
    public function getInboundUri()
    {
        return $this->inbound_uri;
    }

    /**
     * The URI for inbound requests
     *
     * Generated from protobuf field <code>string inbound_uri = 5 [json_name = "inboundUri"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setInboundUri($var)
    {
        GPBUtil::checkString($var, true);
        $this->inbound_uri = $var;

        return $this;
    }

    /**
     * Reference to the AccessControlList
     *
     * Generated from protobuf field <code>string access_control_list_ref = 6 [json_name = "accessControlListRef"];</code>
     *
     * @return string
     */
    public function getAccessControlListRef()
    {
        return $this->access_control_list_ref;
    }

    /**
     * Reference to the AccessControlList
     *
     * Generated from protobuf field <code>string access_control_list_ref = 6 [json_name = "accessControlListRef"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setAccessControlListRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->access_control_list_ref = $var;

        return $this;
    }

    /**
     * Reference to the inbound Credentials
     *
     * Generated from protobuf field <code>string inbound_credentials_ref = 7 [json_name = "inboundCredentialsRef"];</code>
     *
     * @return string
     */
    public function getInboundCredentialsRef()
    {
        return $this->inbound_credentials_ref;
    }

    /**
     * Reference to the inbound Credentials
     *
     * Generated from protobuf field <code>string inbound_credentials_ref = 7 [json_name = "inboundCredentialsRef"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setInboundCredentialsRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->inbound_credentials_ref = $var;

        return $this;
    }

    /**
     * Reference to the outbound Credentials
     *
     * Generated from protobuf field <code>string outbound_credentials_ref = 8 [json_name = "outboundCredentialsRef"];</code>
     *
     * @return string
     */
    public function getOutboundCredentialsRef()
    {
        return $this->outbound_credentials_ref;
    }

    /**
     * Reference to the outbound Credentials
     *
     * Generated from protobuf field <code>string outbound_credentials_ref = 8 [json_name = "outboundCredentialsRef"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setOutboundCredentialsRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->outbound_credentials_ref = $var;

        return $this;
    }

    /**
     * The list of URIs for the Trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.trunks.v2beta1.TrunkURI uris = 9 [json_name = "uris"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUris()
    {
        return $this->uris;
    }

    /**
     * The list of URIs for the Trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.trunks.v2beta1.TrunkURI uris = 9 [json_name = "uris"];</code>
     *
     * @param  array<\Fonoster\Routr\Connect\Trunks\V2beta1\TrunkURI>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUris($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fonoster\Routr\Connect\Trunks\V2beta1\TrunkURI::class);
        $this->uris = $arr;

        return $this;
    }

    /**
     * The extended attributes of the Trunk
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 10 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the Trunk
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 10 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
