<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/peers.proto

namespace Fonoster\Routr\Connect\Peers\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for the Peers.FindBy method
 *
 * Generated from protobuf message <code>fonoster.routr.connect.peers.v2beta1.FindByRequest</code>
 */
class FindByRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The field name to search
     *
     * Generated from protobuf field <code>string fieldName = 1 [json_name = "fieldName"];</code>
     */
    protected $fieldName = '';
    /**
     * The value to search
     *
     * Generated from protobuf field <code>string fieldValue = 2 [json_name = "fieldValue"];</code>
     */
    protected $fieldValue = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $fieldName
     *           The field name to search
     *     @type string $fieldValue
     *           The value to search
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Peers::initOnce();
        parent::__construct($data);
    }

    /**
     * The field name to search
     *
     * Generated from protobuf field <code>string fieldName = 1 [json_name = "fieldName"];</code>
     *
     * @return string
     */
    public function getFieldName()
    {
        return $this->fieldName;
    }

    /**
     * The field name to search
     *
     * Generated from protobuf field <code>string fieldName = 1 [json_name = "fieldName"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, true);
        $this->fieldName = $var;

        return $this;
    }

    /**
     * The value to search
     *
     * Generated from protobuf field <code>string fieldValue = 2 [json_name = "fieldValue"];</code>
     *
     * @return string
     */
    public function getFieldValue()
    {
        return $this->fieldValue;
    }

    /**
     * The value to search
     *
     * Generated from protobuf field <code>string fieldValue = 2 [json_name = "fieldValue"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setFieldValue($var)
    {
        GPBUtil::checkString($var, true);
        $this->fieldValue = $var;

        return $this;
    }
}
