<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/peers.proto

namespace Fonoster\Routr\Connect\Peers\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message for the Peers.FindBy method
 *
 * Generated from protobuf message <code>fonoster.routr.connect.peers.v2beta1.FindByResponse</code>
 */
class FindByResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of Peers items
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.peers.v2beta1.Peer items = 1 [json_name = "items"];</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Fonoster\Routr\Connect\Peers\V2beta1\Peer>|\Google\Protobuf\Internal\RepeatedField $items
     *           The list of Peers items
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Peers::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of Peers items
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.peers.v2beta1.Peer items = 1 [json_name = "items"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * The list of Peers items
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.peers.v2beta1.Peer items = 1 [json_name = "items"];</code>
     *
     * @param  array<\Fonoster\Routr\Connect\Peers\V2beta1\Peer>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fonoster\Routr\Connect\Peers\V2beta1\Peer::class);
        $this->items = $arr;

        return $this;
    }
}
