<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/peers.proto

namespace Fonoster\Routr\Connect\Peers\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for the Peers.Get method
 *
 * Generated from protobuf message <code>fonoster.routr.connect.peers.v2beta1.GetPeerRequest</code>
 */
class GetPeerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier of the Peer
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     */
    protected $ref = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ref
     *           The unique identifier of the Peer
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Peers::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier of the Peer
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The unique identifier of the Peer
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }
}
