<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/peers.proto

namespace Fonoster\Routr\Connect\Peers\V2beta1;

use UnexpectedValueException;

/**
 * Protobuf type <code>fonoster.routr.connect.peers.v2beta1.LoadBalancingAlgorithm</code>
 */
class LoadBalancingAlgorithm
{
    /**
     * Value for situations where the load balancing algorithm is not specified
     * Such as having an aor starting with "sip:"
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * The round robin load balancing algorithm
     *
     * Generated from protobuf enum <code>ROUND_ROBIN = 1;</code>
     */
    const ROUND_ROBIN = 1;
    /**
     * The least sessions load balancing algorithm
     *
     * Generated from protobuf enum <code>LEAST_SESSIONS = 2;</code>
     */
    const LEAST_SESSIONS = 2;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::ROUND_ROBIN => 'ROUND_ROBIN',
        self::LEAST_SESSIONS => 'LEAST_SESSIONS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                __CLASS__,
                $value
            ));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                __CLASS__,
                $name
            ));
        }
        return constant($const);
    }
}
