<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/peers.proto

namespace Fonoster\Routr\Connect\Peers\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for the Peers.Update method
 *
 * Generated from protobuf message <code>fonoster.routr.connect.peers.v2beta1.UpdatePeerRequest</code>
 */
class UpdatePeerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier of the Peer
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     */
    protected $ref = '';
    /**
     * The name of the Peer
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The address of record of the Peer
     *
     * Generated from protobuf field <code>string aor = 3 [json_name = "aor"];</code>
     */
    protected $aor = '';
    /**
     * The contact address of the Peer
     *
     * Generated from protobuf field <code>string contact_addr = 4 [json_name = "contactAddr"];</code>
     */
    protected $contact_addr = '';
    /**
     * The load balancing algorithm of the Peer
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.peers.v2beta1.LoadBalancingAlgorithm balancing_algorithm = 5 [json_name = "balancingAlgorithm"];</code>
     */
    protected $balancing_algorithm = 0;
    /**
     * The session affinity of the Peer
     *
     * Generated from protobuf field <code>bool with_session_affinity = 6 [json_name = "withSessionAffinity"];</code>
     */
    protected $with_session_affinity = false;
    /**
     * Reference to the ACL of the Peer
     *
     * Generated from protobuf field <code>string access_control_list_ref = 7 [json_name = "accessControlListRef"];</code>
     */
    protected $access_control_list_ref = '';
    /**
     * Reference to the Credentials of the Peer
     *
     * Generated from protobuf field <code>string credentials_ref = 8 [json_name = "credentialsRef"];</code>
     */
    protected $credentials_ref = '';
    /**
     * The status of the Peer
     *
     * Generated from protobuf field <code>bool enabled = 9 [json_name = "enabled"];</code>
     */
    protected $enabled = false;
    /**
     * The maximum number of contacts that can be created for this Peer
     *
     * Generated from protobuf field <code>int32 max_contacts = 11 [json_name = "maxContacts"];</code>
     */
    protected $max_contacts = 0;
    /**
     * Value to override the expires requested by the Peer
     *
     * Generated from protobuf field <code>int32 expires = 12 [json_name = "expires"];</code>
     */
    protected $expires = 0;
    /**
     * The extended attributes of the Peer
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 10 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ref
     *           The unique identifier of the Peer
     *     @type string $name
     *           The name of the Peer
     *     @type string $aor
     *           The address of record of the Peer
     *     @type string $contact_addr
     *           The contact address of the Peer
     *     @type int $balancing_algorithm
     *           The load balancing algorithm of the Peer
     *     @type bool $with_session_affinity
     *           The session affinity of the Peer
     *     @type string $access_control_list_ref
     *           Reference to the ACL of the Peer
     *     @type string $credentials_ref
     *           Reference to the Credentials of the Peer
     *     @type bool $enabled
     *           The status of the Peer
     *     @type int $max_contacts
     *           The maximum number of contacts that can be created for this Peer
     *     @type int $expires
     *           Value to override the expires requested by the Peer
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the Peer
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Peers::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier of the Peer
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The unique identifier of the Peer
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * The name of the Peer
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Peer
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The address of record of the Peer
     *
     * Generated from protobuf field <code>string aor = 3 [json_name = "aor"];</code>
     *
     * @return string
     */
    public function getAor()
    {
        return $this->aor;
    }

    /**
     * The address of record of the Peer
     *
     * Generated from protobuf field <code>string aor = 3 [json_name = "aor"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setAor($var)
    {
        GPBUtil::checkString($var, true);
        $this->aor = $var;

        return $this;
    }

    /**
     * The contact address of the Peer
     *
     * Generated from protobuf field <code>string contact_addr = 4 [json_name = "contactAddr"];</code>
     *
     * @return string
     */
    public function getContactAddr()
    {
        return $this->contact_addr;
    }

    /**
     * The contact address of the Peer
     *
     * Generated from protobuf field <code>string contact_addr = 4 [json_name = "contactAddr"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setContactAddr($var)
    {
        GPBUtil::checkString($var, true);
        $this->contact_addr = $var;

        return $this;
    }

    /**
     * The load balancing algorithm of the Peer
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.peers.v2beta1.LoadBalancingAlgorithm balancing_algorithm = 5 [json_name = "balancingAlgorithm"];</code>
     *
     * @return integer
     */
    public function getBalancingAlgorithm()
    {
        return $this->balancing_algorithm;
    }

    /**
     * The load balancing algorithm of the Peer
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.peers.v2beta1.LoadBalancingAlgorithm balancing_algorithm = 5 [json_name = "balancingAlgorithm"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setBalancingAlgorithm($var)
    {
        GPBUtil::checkEnum($var, \Fonoster\Routr\Connect\Peers\V2beta1\LoadBalancingAlgorithm::class);
        $this->balancing_algorithm = $var;

        return $this;
    }

    /**
     * The session affinity of the Peer
     *
     * Generated from protobuf field <code>bool with_session_affinity = 6 [json_name = "withSessionAffinity"];</code>
     *
     * @return boolean
     */
    public function getWithSessionAffinity()
    {
        return $this->with_session_affinity;
    }

    /**
     * The session affinity of the Peer
     *
     * Generated from protobuf field <code>bool with_session_affinity = 6 [json_name = "withSessionAffinity"];</code>
     *
     * @param  boolean $var
     * @return $this
     */
    public function setWithSessionAffinity($var)
    {
        GPBUtil::checkBool($var);
        $this->with_session_affinity = $var;

        return $this;
    }

    /**
     * Reference to the ACL of the Peer
     *
     * Generated from protobuf field <code>string access_control_list_ref = 7 [json_name = "accessControlListRef"];</code>
     *
     * @return string
     */
    public function getAccessControlListRef()
    {
        return $this->access_control_list_ref;
    }

    /**
     * Reference to the ACL of the Peer
     *
     * Generated from protobuf field <code>string access_control_list_ref = 7 [json_name = "accessControlListRef"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setAccessControlListRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->access_control_list_ref = $var;

        return $this;
    }

    /**
     * Reference to the Credentials of the Peer
     *
     * Generated from protobuf field <code>string credentials_ref = 8 [json_name = "credentialsRef"];</code>
     *
     * @return string
     */
    public function getCredentialsRef()
    {
        return $this->credentials_ref;
    }

    /**
     * Reference to the Credentials of the Peer
     *
     * Generated from protobuf field <code>string credentials_ref = 8 [json_name = "credentialsRef"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setCredentialsRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->credentials_ref = $var;

        return $this;
    }

    /**
     * The status of the Peer
     *
     * Generated from protobuf field <code>bool enabled = 9 [json_name = "enabled"];</code>
     *
     * @return boolean
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * The status of the Peer
     *
     * Generated from protobuf field <code>bool enabled = 9 [json_name = "enabled"];</code>
     *
     * @param  boolean $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * The maximum number of contacts that can be created for this Peer
     *
     * Generated from protobuf field <code>int32 max_contacts = 11 [json_name = "maxContacts"];</code>
     *
     * @return integer
     */
    public function getMaxContacts()
    {
        return $this->max_contacts;
    }

    /**
     * The maximum number of contacts that can be created for this Peer
     *
     * Generated from protobuf field <code>int32 max_contacts = 11 [json_name = "maxContacts"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setMaxContacts($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_contacts = $var;

        return $this;
    }

    /**
     * Value to override the expires requested by the Peer
     *
     * Generated from protobuf field <code>int32 expires = 12 [json_name = "expires"];</code>
     *
     * @return integer
     */
    public function getExpires()
    {
        return $this->expires;
    }

    /**
     * Value to override the expires requested by the Peer
     *
     * Generated from protobuf field <code>int32 expires = 12 [json_name = "expires"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setExpires($var)
    {
        GPBUtil::checkInt32($var);
        $this->expires = $var;

        return $this;
    }

    /**
     * The extended attributes of the Peer
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 10 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the Peer
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 10 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
