<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/agents.proto

namespace Fonoster\Routr\Connect\Agents\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The message for the Agent resource
 *
 * Generated from protobuf message <code>fonoster.routr.connect.agents.v2beta1.Agent</code>
 */
class Agent extends \Google\Protobuf\Internal\Message
{
    /**
     * The API version of the Agent
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     */
    protected $api_version = '';
    /**
     * The unique identifier of the Agent
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     */
    protected $ref = '';
    /**
     * The name of the Agent
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The username of the Agent
     *
     * Generated from protobuf field <code>string username = 4 [json_name = "username"];</code>
     */
    protected $username = '';
    /**
     * The password of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.agents.v2beta1.Privacy privacy = 5 [json_name = "privacy"];</code>
     */
    protected $privacy = 0;
    /**
     * The enabled status of the Agent
     *
     * Generated from protobuf field <code>bool enabled = 6 [json_name = "enabled"];</code>
     */
    protected $enabled = false;
    /**
     * The created_at timestamp of the Agent
     *
     * Generated from protobuf field <code>int32 created_at = 7 [json_name = "createdAt"];</code>
     */
    protected $created_at = 0;
    /**
     * The updated_at timestamp of the Agent
     *
     * Generated from protobuf field <code>int32 updated_at = 8 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = 0;
    /**
     * The maximum number of contacts that can be created for this Agent
     *
     * Generated from protobuf field <code>int32 max_contacts = 12 [json_name = "maxContacts"];</code>
     */
    protected $max_contacts = 0;
    /**
     * Value to override the expires requested by the Agent
     *
     * Generated from protobuf field <code>int32 expires = 13 [json_name = "expires"];</code>
     */
    protected $expires = 0;
    /**
     * The domain of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.domains.v2beta1.Domain domain = 9 [json_name = "domain"];</code>
     */
    protected $domain = null;
    /**
     * The credentials of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.credentials.v2beta1.Credentials credentials = 10 [json_name = "credentials"];</code>
     */
    protected $credentials = null;
    /**
     * The extended attributes of the Agent
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 11 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_version
     *           The API version of the Agent
     *     @type string $ref
     *           The unique identifier of the Agent
     *     @type string $name
     *           The name of the Agent
     *     @type string $username
     *           The username of the Agent
     *     @type int $privacy
     *           The password of the Agent
     *     @type bool $enabled
     *           The enabled status of the Agent
     *     @type int $created_at
     *           The created_at timestamp of the Agent
     *     @type int $updated_at
     *           The updated_at timestamp of the Agent
     *     @type int $max_contacts
     *           The maximum number of contacts that can be created for this Agent
     *     @type int $expires
     *           Value to override the expires requested by the Agent
     *     @type \Fonoster\Routr\Connect\Domains\V2beta1\Domain $domain
     *           The domain of the Agent
     *     @type \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials $credentials
     *           The credentials of the Agent
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the Agent
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Agents::initOnce();
        parent::__construct($data);
    }

    /**
     * The API version of the Agent
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @return string
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * The API version of the Agent
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setApiVersion($var)
    {
        GPBUtil::checkString($var, true);
        $this->api_version = $var;

        return $this;
    }

    /**
     * The unique identifier of the Agent
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The unique identifier of the Agent
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * The name of the Agent
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Agent
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The username of the Agent
     *
     * Generated from protobuf field <code>string username = 4 [json_name = "username"];</code>
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * The username of the Agent
     *
     * Generated from protobuf field <code>string username = 4 [json_name = "username"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, true);
        $this->username = $var;

        return $this;
    }

    /**
     * The password of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.agents.v2beta1.Privacy privacy = 5 [json_name = "privacy"];</code>
     *
     * @return integer
     */
    public function getPrivacy()
    {
        return $this->privacy;
    }

    /**
     * The password of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.agents.v2beta1.Privacy privacy = 5 [json_name = "privacy"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setPrivacy($var)
    {
        GPBUtil::checkEnum($var, \Fonoster\Routr\Connect\Agents\V2beta1\Privacy::class);
        $this->privacy = $var;

        return $this;
    }

    /**
     * The enabled status of the Agent
     *
     * Generated from protobuf field <code>bool enabled = 6 [json_name = "enabled"];</code>
     *
     * @return boolean
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * The enabled status of the Agent
     *
     * Generated from protobuf field <code>bool enabled = 6 [json_name = "enabled"];</code>
     *
     * @param  boolean $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * The created_at timestamp of the Agent
     *
     * Generated from protobuf field <code>int32 created_at = 7 [json_name = "createdAt"];</code>
     *
     * @return integer
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * The created_at timestamp of the Agent
     *
     * Generated from protobuf field <code>int32 created_at = 7 [json_name = "createdAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * The updated_at timestamp of the Agent
     *
     * Generated from protobuf field <code>int32 updated_at = 8 [json_name = "updatedAt"];</code>
     *
     * @return integer
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * The updated_at timestamp of the Agent
     *
     * Generated from protobuf field <code>int32 updated_at = 8 [json_name = "updatedAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * The maximum number of contacts that can be created for this Agent
     *
     * Generated from protobuf field <code>int32 max_contacts = 12 [json_name = "maxContacts"];</code>
     *
     * @return integer
     */
    public function getMaxContacts()
    {
        return $this->max_contacts;
    }

    /**
     * The maximum number of contacts that can be created for this Agent
     *
     * Generated from protobuf field <code>int32 max_contacts = 12 [json_name = "maxContacts"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setMaxContacts($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_contacts = $var;

        return $this;
    }

    /**
     * Value to override the expires requested by the Agent
     *
     * Generated from protobuf field <code>int32 expires = 13 [json_name = "expires"];</code>
     *
     * @return integer
     */
    public function getExpires()
    {
        return $this->expires;
    }

    /**
     * Value to override the expires requested by the Agent
     *
     * Generated from protobuf field <code>int32 expires = 13 [json_name = "expires"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setExpires($var)
    {
        GPBUtil::checkInt32($var);
        $this->expires = $var;

        return $this;
    }

    /**
     * The domain of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.domains.v2beta1.Domain domain = 9 [json_name = "domain"];</code>
     *
     * @return \Fonoster\Routr\Connect\Domains\V2beta1\Domain|null
     */
    public function getDomain()
    {
        return $this->domain;
    }

    public function hasDomain()
    {
        return isset($this->domain);
    }

    public function clearDomain()
    {
        unset($this->domain);
    }

    /**
     * The domain of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.domains.v2beta1.Domain domain = 9 [json_name = "domain"];</code>
     *
     * @param  \Fonoster\Routr\Connect\Domains\V2beta1\Domain $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkMessage($var, \Fonoster\Routr\Connect\Domains\V2beta1\Domain::class);
        $this->domain = $var;

        return $this;
    }

    /**
     * The credentials of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.credentials.v2beta1.Credentials credentials = 10 [json_name = "credentials"];</code>
     *
     * @return \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials|null
     */
    public function getCredentials()
    {
        return $this->credentials;
    }

    public function hasCredentials()
    {
        return isset($this->credentials);
    }

    public function clearCredentials()
    {
        unset($this->credentials);
    }

    /**
     * The credentials of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.credentials.v2beta1.Credentials credentials = 10 [json_name = "credentials"];</code>
     *
     * @param  \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials $var
     * @return $this
     */
    public function setCredentials($var)
    {
        GPBUtil::checkMessage($var, \Fonoster\Routr\Connect\Credentials\V2beta1\Credentials::class);
        $this->credentials = $var;

        return $this;
    }

    /**
     * The extended attributes of the Agent
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 11 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the Agent
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 11 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
