<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/agents.proto

namespace Fonoster\Routr\Connect\Agents\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for the Agents.Create method
 *
 * Generated from protobuf message <code>fonoster.routr.connect.agents.v2beta1.CreateAgentRequest</code>
 */
class CreateAgentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the Agent
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The username of the Agent
     *
     * Generated from protobuf field <code>string username = 2 [json_name = "username"];</code>
     */
    protected $username = '';
    /**
     * The password of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.agents.v2beta1.Privacy privacy = 3 [json_name = "privacy"];</code>
     */
    protected $privacy = 0;
    /**
     * The enabled status of the Agent
     *
     * Generated from protobuf field <code>bool enabled = 4 [json_name = "enabled"];</code>
     */
    protected $enabled = false;
    /**
     * Reference to the Domain of the Agent
     *
     * Generated from protobuf field <code>string domain_ref = 5 [json_name = "domainRef"];</code>
     */
    protected $domain_ref = '';
    /**
     * Reference to the Credentials of the Agent
     *
     * Generated from protobuf field <code>string credentials_ref = 6 [json_name = "credentialsRef"];</code>
     */
    protected $credentials_ref = '';
    /**
     * The maximum number of contacts that can be created for this Agent
     *
     * Generated from protobuf field <code>int32 max_contacts = 8 [json_name = "maxContacts"];</code>
     */
    protected $max_contacts = 0;
    /**
     * Value to override the expires requested by the Agent
     *
     * Generated from protobuf field <code>int32 expires = 9 [json_name = "expires"];</code>
     */
    protected $expires = 0;
    /**
     * The extended attributes of the Agent
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 7 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the Agent
     *     @type string $username
     *           The username of the Agent
     *     @type int $privacy
     *           The password of the Agent
     *     @type bool $enabled
     *           The enabled status of the Agent
     *     @type string $domain_ref
     *           Reference to the Domain of the Agent
     *     @type string $credentials_ref
     *           Reference to the Credentials of the Agent
     *     @type int $max_contacts
     *           The maximum number of contacts that can be created for this Agent
     *     @type int $expires
     *           Value to override the expires requested by the Agent
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the Agent
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Agents::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the Agent
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Agent
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The username of the Agent
     *
     * Generated from protobuf field <code>string username = 2 [json_name = "username"];</code>
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * The username of the Agent
     *
     * Generated from protobuf field <code>string username = 2 [json_name = "username"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, true);
        $this->username = $var;

        return $this;
    }

    /**
     * The password of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.agents.v2beta1.Privacy privacy = 3 [json_name = "privacy"];</code>
     *
     * @return integer
     */
    public function getPrivacy()
    {
        return $this->privacy;
    }

    /**
     * The password of the Agent
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.agents.v2beta1.Privacy privacy = 3 [json_name = "privacy"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setPrivacy($var)
    {
        GPBUtil::checkEnum($var, \Fonoster\Routr\Connect\Agents\V2beta1\Privacy::class);
        $this->privacy = $var;

        return $this;
    }

    /**
     * The enabled status of the Agent
     *
     * Generated from protobuf field <code>bool enabled = 4 [json_name = "enabled"];</code>
     *
     * @return boolean
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * The enabled status of the Agent
     *
     * Generated from protobuf field <code>bool enabled = 4 [json_name = "enabled"];</code>
     *
     * @param  boolean $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Reference to the Domain of the Agent
     *
     * Generated from protobuf field <code>string domain_ref = 5 [json_name = "domainRef"];</code>
     *
     * @return string
     */
    public function getDomainRef()
    {
        return $this->domain_ref;
    }

    /**
     * Reference to the Domain of the Agent
     *
     * Generated from protobuf field <code>string domain_ref = 5 [json_name = "domainRef"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setDomainRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->domain_ref = $var;

        return $this;
    }

    /**
     * Reference to the Credentials of the Agent
     *
     * Generated from protobuf field <code>string credentials_ref = 6 [json_name = "credentialsRef"];</code>
     *
     * @return string
     */
    public function getCredentialsRef()
    {
        return $this->credentials_ref;
    }

    /**
     * Reference to the Credentials of the Agent
     *
     * Generated from protobuf field <code>string credentials_ref = 6 [json_name = "credentialsRef"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setCredentialsRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->credentials_ref = $var;

        return $this;
    }

    /**
     * The maximum number of contacts that can be created for this Agent
     *
     * Generated from protobuf field <code>int32 max_contacts = 8 [json_name = "maxContacts"];</code>
     *
     * @return integer
     */
    public function getMaxContacts()
    {
        return $this->max_contacts;
    }

    /**
     * The maximum number of contacts that can be created for this Agent
     *
     * Generated from protobuf field <code>int32 max_contacts = 8 [json_name = "maxContacts"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setMaxContacts($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_contacts = $var;

        return $this;
    }

    /**
     * Value to override the expires requested by the Agent
     *
     * Generated from protobuf field <code>int32 expires = 9 [json_name = "expires"];</code>
     *
     * @return integer
     */
    public function getExpires()
    {
        return $this->expires;
    }

    /**
     * Value to override the expires requested by the Agent
     *
     * Generated from protobuf field <code>int32 expires = 9 [json_name = "expires"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setExpires($var)
    {
        GPBUtil::checkInt32($var);
        $this->expires = $var;

        return $this;
    }

    /**
     * The extended attributes of the Agent
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 7 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the Agent
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 7 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
