<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/agents.proto

namespace Fonoster\Routr\Connect\Agents\V2beta1;

use UnexpectedValueException;

/**
 * Protobuf type <code>fonoster.routr.connect.agents.v2beta1.Privacy</code>
 */
class Privacy
{
    /**
     * Generated from protobuf enum <code>PRIVATE = 0;</code>
     */
    const PBPRIVATE = 0;
    /**
     * Generated from protobuf enum <code>NONE = 1;</code>
     */
    const NONE = 1;

    private static $valueToName = [
        self::PBPRIVATE => 'PRIVATE',
        self::NONE => 'NONE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                __CLASS__,
                $value
            ));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  __CLASS__ . '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s',
                    __CLASS__,
                    $name
                ));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}
