<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/credentials.proto

namespace Fonoster\Routr\Connect\Credentials\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for the CreateCredentials.Create method
 *
 * Generated from protobuf message <code>fonoster.routr.connect.credentials.v2beta1.CreateCredentialsRequest</code>
 */
class CreateCredentialsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the Credentials
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The username of the Credentials
     *
     * Generated from protobuf field <code>string username = 2 [json_name = "username"];</code>
     */
    protected $username = '';
    /**
     * The password of the Credentials
     *
     * Generated from protobuf field <code>string password = 3 [json_name = "password"];</code>
     */
    protected $password = '';
    /**
     * The extended attributes for a set of Credentials
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 4 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the Credentials
     *     @type string $username
     *           The username of the Credentials
     *     @type string $password
     *           The password of the Credentials
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes for a set of Credentials
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Credentials::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the Credentials
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Credentials
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The username of the Credentials
     *
     * Generated from protobuf field <code>string username = 2 [json_name = "username"];</code>
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * The username of the Credentials
     *
     * Generated from protobuf field <code>string username = 2 [json_name = "username"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, true);
        $this->username = $var;

        return $this;
    }

    /**
     * The password of the Credentials
     *
     * Generated from protobuf field <code>string password = 3 [json_name = "password"];</code>
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * The password of the Credentials
     *
     * Generated from protobuf field <code>string password = 3 [json_name = "password"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, true);
        $this->password = $var;

        return $this;
    }

    /**
     * The extended attributes for a set of Credentials
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 4 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes for a set of Credentials
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 4 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
