<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/credentials.proto

namespace Fonoster\Routr\Connect\Credentials\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The message for the Credentials resource
 *
 * Generated from protobuf message <code>fonoster.routr.connect.credentials.v2beta1.Credentials</code>
 */
class Credentials extends \Google\Protobuf\Internal\Message
{
    /**
     * The API version of the Credentials
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     */
    protected $api_version = '';
    /**
     * The reference of the Credentials
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     */
    protected $ref = '';
    /**
     * The name of the Credentials
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The username of the Credentials
     *
     * Generated from protobuf field <code>string username = 4 [json_name = "username"];</code>
     */
    protected $username = '';
    /**
     * The password of the Credentials
     *
     * Generated from protobuf field <code>string password = 5 [json_name = "password"];</code>
     */
    protected $password = '';
    /**
     * The time the Credentials was created
     *
     * Generated from protobuf field <code>int32 created_at = 6 [json_name = "createdAt"];</code>
     */
    protected $created_at = 0;
    /**
     * The time the Credentials was updated
     *
     * Generated from protobuf field <code>int32 updated_at = 7 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = 0;
    /**
     * The extended attributes for a set of Credentials
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 8 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_version
     *           The API version of the Credentials
     *     @type string $ref
     *           The reference of the Credentials
     *     @type string $name
     *           The name of the Credentials
     *     @type string $username
     *           The username of the Credentials
     *     @type string $password
     *           The password of the Credentials
     *     @type int $created_at
     *           The time the Credentials was created
     *     @type int $updated_at
     *           The time the Credentials was updated
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes for a set of Credentials
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Credentials::initOnce();
        parent::__construct($data);
    }

    /**
     * The API version of the Credentials
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @return string
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * The API version of the Credentials
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setApiVersion($var)
    {
        GPBUtil::checkString($var, true);
        $this->api_version = $var;

        return $this;
    }

    /**
     * The reference of the Credentials
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The reference of the Credentials
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * The name of the Credentials
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Credentials
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The username of the Credentials
     *
     * Generated from protobuf field <code>string username = 4 [json_name = "username"];</code>
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * The username of the Credentials
     *
     * Generated from protobuf field <code>string username = 4 [json_name = "username"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, true);
        $this->username = $var;

        return $this;
    }

    /**
     * The password of the Credentials
     *
     * Generated from protobuf field <code>string password = 5 [json_name = "password"];</code>
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * The password of the Credentials
     *
     * Generated from protobuf field <code>string password = 5 [json_name = "password"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, true);
        $this->password = $var;

        return $this;
    }

    /**
     * The time the Credentials was created
     *
     * Generated from protobuf field <code>int32 created_at = 6 [json_name = "createdAt"];</code>
     *
     * @return integer
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * The time the Credentials was created
     *
     * Generated from protobuf field <code>int32 created_at = 6 [json_name = "createdAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * The time the Credentials was updated
     *
     * Generated from protobuf field <code>int32 updated_at = 7 [json_name = "updatedAt"];</code>
     *
     * @return integer
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * The time the Credentials was updated
     *
     * Generated from protobuf field <code>int32 updated_at = 7 [json_name = "updatedAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * The extended attributes for a set of Credentials
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 8 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes for a set of Credentials
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 8 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
