<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/credentials.proto

namespace Fonoster\Routr\Connect\Credentials\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for the ListCredentials.List method
 *
 * Generated from protobuf message <code>fonoster.routr.connect.credentials.v2beta1.ListCredentialsRequest</code>
 */
class ListCredentialsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The maximum number of items in the list
     *
     * Generated from protobuf field <code>int32 page_size = 1 [json_name = "pageSize"];</code>
     */
    protected $page_size = 0;
    /**
     * The next_page_token value returned from the previous request, if any
     *
     * Generated from protobuf field <code>string page_token = 2 [json_name = "pageToken"];</code>
     */
    protected $page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $page_size
     *           The maximum number of items in the list
     *     @type string $page_token
     *           The next_page_token value returned from the previous request, if any
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Credentials::initOnce();
        parent::__construct($data);
    }

    /**
     * The maximum number of items in the list
     *
     * Generated from protobuf field <code>int32 page_size = 1 [json_name = "pageSize"];</code>
     *
     * @return integer
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * The maximum number of items in the list
     *
     * Generated from protobuf field <code>int32 page_size = 1 [json_name = "pageSize"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * The next_page_token value returned from the previous request, if any
     *
     * Generated from protobuf field <code>string page_token = 2 [json_name = "pageToken"];</code>
     *
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * The next_page_token value returned from the previous request, if any
     *
     * Generated from protobuf field <code>string page_token = 2 [json_name = "pageToken"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, true);
        $this->page_token = $var;

        return $this;
    }
}
