<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/domains.proto

namespace Fonoster\Routr\Connect\Domains\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The message for the Domain resource
 *
 * Generated from protobuf message <code>fonoster.routr.connect.domains.v2beta1.Domain</code>
 */
class Domain extends \Google\Protobuf\Internal\Message
{
    /**
     * The API version of the Domain
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     */
    protected $api_version = '';
    /**
     * The unique identifier of the Domain
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     */
    protected $ref = '';
    /**
     * The name of the Domain
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The URI of the Domain
     *
     * Generated from protobuf field <code>string domain_uri = 4 [json_name = "domainUri"];</code>
     */
    protected $domain_uri = '';
    /**
     * The date of creation of the Domain
     *
     * Generated from protobuf field <code>int32 created_at = 5 [json_name = "createdAt"];</code>
     */
    protected $created_at = 0;
    /**
     * The date of the last update
     *
     * Generated from protobuf field <code>int32 updated_at = 6 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = 0;
    /**
     * The list of IP addresses that are allowed to access the Domain
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.acl.v2beta1.AccessControlList access_control_list = 7 [json_name = "accessControlList"];</code>
     */
    protected $access_control_list = null;
    /**
     * The egress_policy of the Domain
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.domains.v2beta1.EgressPolicy egress_policies = 8 [json_name = "egressPolicies"];</code>
     */
    private $egress_policies;
    /**
     * The extended attributes of the Domain
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 9 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_version
     *           The API version of the Domain
     *     @type string $ref
     *           The unique identifier of the Domain
     *     @type string $name
     *           The name of the Domain
     *     @type string $domain_uri
     *           The URI of the Domain
     *     @type int $created_at
     *           The date of creation of the Domain
     *     @type int $updated_at
     *           The date of the last update
     *     @type \Fonoster\Routr\Connect\Acl\V2beta1\AccessControlList $access_control_list
     *           The list of IP addresses that are allowed to access the Domain
     *     @type array<\Fonoster\Routr\Connect\Domains\V2beta1\EgressPolicy>|\Google\Protobuf\Internal\RepeatedField $egress_policies
     *           The egress_policy of the Domain
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the Domain
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Domains::initOnce();
        parent::__construct($data);
    }

    /**
     * The API version of the Domain
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @return string
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * The API version of the Domain
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setApiVersion($var)
    {
        GPBUtil::checkString($var, true);
        $this->api_version = $var;

        return $this;
    }

    /**
     * The unique identifier of the Domain
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The unique identifier of the Domain
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * The name of the Domain
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Domain
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The URI of the Domain
     *
     * Generated from protobuf field <code>string domain_uri = 4 [json_name = "domainUri"];</code>
     *
     * @return string
     */
    public function getDomainUri()
    {
        return $this->domain_uri;
    }

    /**
     * The URI of the Domain
     *
     * Generated from protobuf field <code>string domain_uri = 4 [json_name = "domainUri"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setDomainUri($var)
    {
        GPBUtil::checkString($var, true);
        $this->domain_uri = $var;

        return $this;
    }

    /**
     * The date of creation of the Domain
     *
     * Generated from protobuf field <code>int32 created_at = 5 [json_name = "createdAt"];</code>
     *
     * @return integer
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * The date of creation of the Domain
     *
     * Generated from protobuf field <code>int32 created_at = 5 [json_name = "createdAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * The date of the last update
     *
     * Generated from protobuf field <code>int32 updated_at = 6 [json_name = "updatedAt"];</code>
     *
     * @return integer
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * The date of the last update
     *
     * Generated from protobuf field <code>int32 updated_at = 6 [json_name = "updatedAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * The list of IP addresses that are allowed to access the Domain
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.acl.v2beta1.AccessControlList access_control_list = 7 [json_name = "accessControlList"];</code>
     *
     * @return \Fonoster\Routr\Connect\Acl\V2beta1\AccessControlList|null
     */
    public function getAccessControlList()
    {
        return $this->access_control_list;
    }

    public function hasAccessControlList()
    {
        return isset($this->access_control_list);
    }

    public function clearAccessControlList()
    {
        unset($this->access_control_list);
    }

    /**
     * The list of IP addresses that are allowed to access the Domain
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.acl.v2beta1.AccessControlList access_control_list = 7 [json_name = "accessControlList"];</code>
     *
     * @param  \Fonoster\Routr\Connect\Acl\V2beta1\AccessControlList $var
     * @return $this
     */
    public function setAccessControlList($var)
    {
        GPBUtil::checkMessage($var, \Fonoster\Routr\Connect\Acl\V2beta1\AccessControlList::class);
        $this->access_control_list = $var;

        return $this;
    }

    /**
     * The egress_policy of the Domain
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.domains.v2beta1.EgressPolicy egress_policies = 8 [json_name = "egressPolicies"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEgressPolicies()
    {
        return $this->egress_policies;
    }

    /**
     * The egress_policy of the Domain
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.domains.v2beta1.EgressPolicy egress_policies = 8 [json_name = "egressPolicies"];</code>
     *
     * @param  array<\Fonoster\Routr\Connect\Domains\V2beta1\EgressPolicy>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEgressPolicies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fonoster\Routr\Connect\Domains\V2beta1\EgressPolicy::class);
        $this->egress_policies = $arr;

        return $this;
    }

    /**
     * The extended attributes of the Domain
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 9 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the Domain
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 9 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
