<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/domains.proto

namespace Fonoster\Routr\Connect\Domains\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * EgressPolicy defines the policy for egress traffic
 *
 * Generated from protobuf message <code>fonoster.routr.connect.domains.v2beta1.EgressPolicy</code>
 */
class EgressPolicy extends \Google\Protobuf\Internal\Message
{
    /**
     * The pattern to match
     *
     * Generated from protobuf field <code>string rule = 1 [json_name = "rule"];</code>
     */
    protected $rule = '';
    /**
     * Reference to the number to use for egress
     *
     * Generated from protobuf field <code>string number_ref = 2 [json_name = "numberRef"];</code>
     */
    protected $number_ref = '';
    /**
     * The egress Number
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.numbers.v2beta1.Number number = 3 [json_name = "number"];</code>
     */
    protected $number = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $rule
     *           The pattern to match
     *     @type string $number_ref
     *           Reference to the number to use for egress
     *     @type \Fonoster\Routr\Connect\Numbers\V2beta1\Number $number
     *           The egress Number
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Domains::initOnce();
        parent::__construct($data);
    }

    /**
     * The pattern to match
     *
     * Generated from protobuf field <code>string rule = 1 [json_name = "rule"];</code>
     *
     * @return string
     */
    public function getRule()
    {
        return $this->rule;
    }

    /**
     * The pattern to match
     *
     * Generated from protobuf field <code>string rule = 1 [json_name = "rule"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRule($var)
    {
        GPBUtil::checkString($var, true);
        $this->rule = $var;

        return $this;
    }

    /**
     * Reference to the number to use for egress
     *
     * Generated from protobuf field <code>string number_ref = 2 [json_name = "numberRef"];</code>
     *
     * @return string
     */
    public function getNumberRef()
    {
        return $this->number_ref;
    }

    /**
     * Reference to the number to use for egress
     *
     * Generated from protobuf field <code>string number_ref = 2 [json_name = "numberRef"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setNumberRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->number_ref = $var;

        return $this;
    }

    /**
     * The egress Number
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.numbers.v2beta1.Number number = 3 [json_name = "number"];</code>
     *
     * @return \Fonoster\Routr\Connect\Numbers\V2beta1\Number|null
     */
    public function getNumber()
    {
        return $this->number;
    }

    public function hasNumber()
    {
        return isset($this->number);
    }

    public function clearNumber()
    {
        unset($this->number);
    }

    /**
     * The egress Number
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.numbers.v2beta1.Number number = 3 [json_name = "number"];</code>
     *
     * @param  \Fonoster\Routr\Connect\Numbers\V2beta1\Number $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkMessage($var, \Fonoster\Routr\Connect\Numbers\V2beta1\Number::class);
        $this->number = $var;

        return $this;
    }
}
