<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/domains.proto

namespace Fonoster\Routr\Connect\Domains\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for Domains.Update
 *
 * Generated from protobuf message <code>fonoster.routr.connect.domains.v2beta1.UpdateDomainRequest</code>
 */
class UpdateDomainRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier of the Domain
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     */
    protected $ref = '';
    /**
     * The name of the Domain
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Reference to the ACL to use for this Domain
     *
     * Generated from protobuf field <code>string access_control_list_ref = 3 [json_name = "accessControlListRef"];</code>
     */
    protected $access_control_list_ref = '';
    /**
     * The egress_policy of the Domain
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.domains.v2beta1.EgressPolicy egress_policies = 4 [json_name = "egressPolicies"];</code>
     */
    private $egress_policies;
    /**
     * The extended attributes of the Domain
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 5 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ref
     *           The unique identifier of the Domain
     *     @type string $name
     *           The name of the Domain
     *     @type string $access_control_list_ref
     *           Reference to the ACL to use for this Domain
     *     @type array<\Fonoster\Routr\Connect\Domains\V2beta1\EgressPolicy>|\Google\Protobuf\Internal\RepeatedField $egress_policies
     *           The egress_policy of the Domain
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the Domain
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Domains::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier of the Domain
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The unique identifier of the Domain
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * The name of the Domain
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Domain
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Reference to the ACL to use for this Domain
     *
     * Generated from protobuf field <code>string access_control_list_ref = 3 [json_name = "accessControlListRef"];</code>
     *
     * @return string
     */
    public function getAccessControlListRef()
    {
        return $this->access_control_list_ref;
    }

    /**
     * Reference to the ACL to use for this Domain
     *
     * Generated from protobuf field <code>string access_control_list_ref = 3 [json_name = "accessControlListRef"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setAccessControlListRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->access_control_list_ref = $var;

        return $this;
    }

    /**
     * The egress_policy of the Domain
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.domains.v2beta1.EgressPolicy egress_policies = 4 [json_name = "egressPolicies"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEgressPolicies()
    {
        return $this->egress_policies;
    }

    /**
     * The egress_policy of the Domain
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.domains.v2beta1.EgressPolicy egress_policies = 4 [json_name = "egressPolicies"];</code>
     *
     * @param  array<\Fonoster\Routr\Connect\Domains\V2beta1\EgressPolicy>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEgressPolicies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fonoster\Routr\Connect\Domains\V2beta1\EgressPolicy::class);
        $this->egress_policies = $arr;

        return $this;
    }

    /**
     * The extended attributes of the Domain
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 5 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the Domain
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 5 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
