<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/numbers.proto

namespace Fonoster\Routr\Connect\Numbers\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fonoster.routr.connect.numbers.v2beta1.ListNumbersResponse</code>
 */
class ListNumbersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * List of Numbers
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.numbers.v2beta1.Number items = 1 [json_name = "items"];</code>
     */
    private $items;
    /**
     * Token to retrieve the next page of results, or empty if there are no more results in the list
     *
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Fonoster\Routr\Connect\Numbers\V2beta1\Number>|\Google\Protobuf\Internal\RepeatedField $items
     *           List of Numbers
     *     @type string $next_page_token
     *           Token to retrieve the next page of results, or empty if there are no more results in the list
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Numbers::initOnce();
        parent::__construct($data);
    }

    /**
     * List of Numbers
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.numbers.v2beta1.Number items = 1 [json_name = "items"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * List of Numbers
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.numbers.v2beta1.Number items = 1 [json_name = "items"];</code>
     *
     * @param  array<\Fonoster\Routr\Connect\Numbers\V2beta1\Number>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fonoster\Routr\Connect\Numbers\V2beta1\Number::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more results in the list
     *
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
     *
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to retrieve the next page of results, or empty if there are no more results in the list
     *
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, true);
        $this->next_page_token = $var;

        return $this;
    }
}
