<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/numbers.proto

namespace Fonoster\Routr\Connect\Numbers\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The message for the Number resource
 *
 * Generated from protobuf message <code>fonoster.routr.connect.numbers.v2beta1.Number</code>
 */
class Number extends \Google\Protobuf\Internal\Message
{
    /**
     * The version of the Number
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     */
    protected $api_version = '';
    /**
     * The unique identifier of the Number
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     */
    protected $ref = '';
    /**
     * The name of the Number
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The tel_url of the Number
     *
     * Generated from protobuf field <code>string tel_url = 4 [json_name = "telUrl"];</code>
     */
    protected $tel_url = '';
    /**
     * The aor_link of the Number
     *
     * Generated from protobuf field <code>string aor_link = 5 [json_name = "aorLink"];</code>
     */
    protected $aor_link = '';
    /**
     * The city of the Number
     *
     * Generated from protobuf field <code>string city = 6 [json_name = "city"];</code>
     */
    protected $city = '';
    /**
     * The country of the Number
     *
     * Generated from protobuf field <code>string country = 7 [json_name = "country"];</code>
     */
    protected $country = '';
    /**
     * The country_iso_code of the Number
     *
     * Generated from protobuf field <code>string country_iso_code = 8 [json_name = "countryIsoCode"];</code>
     */
    protected $country_iso_code = '';
    /**
     * The header to use for session affinity
     *
     * Generated from protobuf field <code>string session_affinity_header = 9 [json_name = "sessionAffinityHeader"];</code>
     */
    protected $session_affinity_header = '';
    /**
     * Extra headers to send to the trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.numbers.v2beta1.ExtraHeader extra_headers = 10 [json_name = "extraHeaders"];</code>
     */
    private $extra_headers;
    /**
     * The date when the Number was created
     *
     * Generated from protobuf field <code>int32 created_at = 11 [json_name = "createdAt"];</code>
     */
    protected $created_at = 0;
    /**
     * The date when the Number was last updated
     *
     * Generated from protobuf field <code>int32 updated_at = 12 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = 0;
    /**
     * The trunk this number is associated with
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.trunks.v2beta1.Trunk trunk = 13 [json_name = "trunk"];</code>
     */
    protected $trunk = null;
    /**
     * The extended attributes of the Number
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 14 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_version
     *           The version of the Number
     *     @type string $ref
     *           The unique identifier of the Number
     *     @type string $name
     *           The name of the Number
     *     @type string $tel_url
     *           The tel_url of the Number
     *     @type string $aor_link
     *           The aor_link of the Number
     *     @type string $city
     *           The city of the Number
     *     @type string $country
     *           The country of the Number
     *     @type string $country_iso_code
     *           The country_iso_code of the Number
     *     @type string $session_affinity_header
     *           The header to use for session affinity
     *     @type array<\Fonoster\Routr\Connect\Numbers\V2beta1\ExtraHeader>|\Google\Protobuf\Internal\RepeatedField $extra_headers
     *           Extra headers to send to the trunk
     *     @type int $created_at
     *           The date when the Number was created
     *     @type int $updated_at
     *           The date when the Number was last updated
     *     @type \Fonoster\Routr\Connect\Trunks\V2beta1\Trunk $trunk
     *           The trunk this number is associated with
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the Number
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Numbers::initOnce();
        parent::__construct($data);
    }

    /**
     * The version of the Number
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @return string
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * The version of the Number
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setApiVersion($var)
    {
        GPBUtil::checkString($var, true);
        $this->api_version = $var;

        return $this;
    }

    /**
     * The unique identifier of the Number
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The unique identifier of the Number
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * The name of the Number
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Number
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The tel_url of the Number
     *
     * Generated from protobuf field <code>string tel_url = 4 [json_name = "telUrl"];</code>
     *
     * @return string
     */
    public function getTelUrl()
    {
        return $this->tel_url;
    }

    /**
     * The tel_url of the Number
     *
     * Generated from protobuf field <code>string tel_url = 4 [json_name = "telUrl"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setTelUrl($var)
    {
        GPBUtil::checkString($var, true);
        $this->tel_url = $var;

        return $this;
    }

    /**
     * The aor_link of the Number
     *
     * Generated from protobuf field <code>string aor_link = 5 [json_name = "aorLink"];</code>
     *
     * @return string
     */
    public function getAorLink()
    {
        return $this->aor_link;
    }

    /**
     * The aor_link of the Number
     *
     * Generated from protobuf field <code>string aor_link = 5 [json_name = "aorLink"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setAorLink($var)
    {
        GPBUtil::checkString($var, true);
        $this->aor_link = $var;

        return $this;
    }

    /**
     * The city of the Number
     *
     * Generated from protobuf field <code>string city = 6 [json_name = "city"];</code>
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * The city of the Number
     *
     * Generated from protobuf field <code>string city = 6 [json_name = "city"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, true);
        $this->city = $var;

        return $this;
    }

    /**
     * The country of the Number
     *
     * Generated from protobuf field <code>string country = 7 [json_name = "country"];</code>
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * The country of the Number
     *
     * Generated from protobuf field <code>string country = 7 [json_name = "country"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, true);
        $this->country = $var;

        return $this;
    }

    /**
     * The country_iso_code of the Number
     *
     * Generated from protobuf field <code>string country_iso_code = 8 [json_name = "countryIsoCode"];</code>
     *
     * @return string
     */
    public function getCountryIsoCode()
    {
        return $this->country_iso_code;
    }

    /**
     * The country_iso_code of the Number
     *
     * Generated from protobuf field <code>string country_iso_code = 8 [json_name = "countryIsoCode"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setCountryIsoCode($var)
    {
        GPBUtil::checkString($var, true);
        $this->country_iso_code = $var;

        return $this;
    }

    /**
     * The header to use for session affinity
     *
     * Generated from protobuf field <code>string session_affinity_header = 9 [json_name = "sessionAffinityHeader"];</code>
     *
     * @return string
     */
    public function getSessionAffinityHeader()
    {
        return $this->session_affinity_header;
    }

    /**
     * The header to use for session affinity
     *
     * Generated from protobuf field <code>string session_affinity_header = 9 [json_name = "sessionAffinityHeader"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setSessionAffinityHeader($var)
    {
        GPBUtil::checkString($var, true);
        $this->session_affinity_header = $var;

        return $this;
    }

    /**
     * Extra headers to send to the trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.numbers.v2beta1.ExtraHeader extra_headers = 10 [json_name = "extraHeaders"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtraHeaders()
    {
        return $this->extra_headers;
    }

    /**
     * Extra headers to send to the trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.numbers.v2beta1.ExtraHeader extra_headers = 10 [json_name = "extraHeaders"];</code>
     *
     * @param  array<\Fonoster\Routr\Connect\Numbers\V2beta1\ExtraHeader>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtraHeaders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fonoster\Routr\Connect\Numbers\V2beta1\ExtraHeader::class);
        $this->extra_headers = $arr;

        return $this;
    }

    /**
     * The date when the Number was created
     *
     * Generated from protobuf field <code>int32 created_at = 11 [json_name = "createdAt"];</code>
     *
     * @return integer
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * The date when the Number was created
     *
     * Generated from protobuf field <code>int32 created_at = 11 [json_name = "createdAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * The date when the Number was last updated
     *
     * Generated from protobuf field <code>int32 updated_at = 12 [json_name = "updatedAt"];</code>
     *
     * @return integer
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * The date when the Number was last updated
     *
     * Generated from protobuf field <code>int32 updated_at = 12 [json_name = "updatedAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * The trunk this number is associated with
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.trunks.v2beta1.Trunk trunk = 13 [json_name = "trunk"];</code>
     *
     * @return \Fonoster\Routr\Connect\Trunks\V2beta1\Trunk|null
     */
    public function getTrunk()
    {
        return $this->trunk;
    }

    public function hasTrunk()
    {
        return isset($this->trunk);
    }

    public function clearTrunk()
    {
        unset($this->trunk);
    }

    /**
     * The trunk this number is associated with
     *
     * Generated from protobuf field <code>.fonoster.routr.connect.trunks.v2beta1.Trunk trunk = 13 [json_name = "trunk"];</code>
     *
     * @param  \Fonoster\Routr\Connect\Trunks\V2beta1\Trunk $var
     * @return $this
     */
    public function setTrunk($var)
    {
        GPBUtil::checkMessage($var, \Fonoster\Routr\Connect\Trunks\V2beta1\Trunk::class);
        $this->trunk = $var;

        return $this;
    }

    /**
     * The extended attributes of the Number
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 14 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the Number
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 14 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
