<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/numbers.proto

namespace Fonoster\Routr\Connect\Numbers\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for Numbers.Update
 *
 * Generated from protobuf message <code>fonoster.routr.connect.numbers.v2beta1.UpdateNumberRequest</code>
 */
class UpdateNumberRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier of the Number
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     */
    protected $ref = '';
    /**
     * The name of the Number
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The aor_link of the Number
     *
     * Generated from protobuf field <code>string aor_link = 4 [json_name = "aorLink"];</code>
     */
    protected $aor_link = '';
    /**
     * The header to use for session affinity
     *
     * Generated from protobuf field <code>string session_affinity_header = 8 [json_name = "sessionAffinityHeader"];</code>
     */
    protected $session_affinity_header = '';
    /**
     * Extra headers to send to the trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.numbers.v2beta1.ExtraHeader extra_headers = 9 [json_name = "extraHeaders"];</code>
     */
    private $extra_headers;
    /**
     * Reference to the trunk this number is associated with
     *
     * Generated from protobuf field <code>string trunk_ref = 10 [json_name = "trunkRef"];</code>
     */
    protected $trunk_ref = '';
    /**
     * The extended attributes of the Number
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 11 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ref
     *           The unique identifier of the Number
     *     @type string $name
     *           The name of the Number
     *     @type string $aor_link
     *           The aor_link of the Number
     *     @type string $session_affinity_header
     *           The header to use for session affinity
     *     @type array<\Fonoster\Routr\Connect\Numbers\V2beta1\ExtraHeader>|\Google\Protobuf\Internal\RepeatedField $extra_headers
     *           Extra headers to send to the trunk
     *     @type string $trunk_ref
     *           Reference to the trunk this number is associated with
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the Number
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Numbers::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier of the Number
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The unique identifier of the Number
     *
     * Generated from protobuf field <code>string ref = 1 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * The name of the Number
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the Number
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The aor_link of the Number
     *
     * Generated from protobuf field <code>string aor_link = 4 [json_name = "aorLink"];</code>
     *
     * @return string
     */
    public function getAorLink()
    {
        return $this->aor_link;
    }

    /**
     * The aor_link of the Number
     *
     * Generated from protobuf field <code>string aor_link = 4 [json_name = "aorLink"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setAorLink($var)
    {
        GPBUtil::checkString($var, true);
        $this->aor_link = $var;

        return $this;
    }

    /**
     * The header to use for session affinity
     *
     * Generated from protobuf field <code>string session_affinity_header = 8 [json_name = "sessionAffinityHeader"];</code>
     *
     * @return string
     */
    public function getSessionAffinityHeader()
    {
        return $this->session_affinity_header;
    }

    /**
     * The header to use for session affinity
     *
     * Generated from protobuf field <code>string session_affinity_header = 8 [json_name = "sessionAffinityHeader"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setSessionAffinityHeader($var)
    {
        GPBUtil::checkString($var, true);
        $this->session_affinity_header = $var;

        return $this;
    }

    /**
     * Extra headers to send to the trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.numbers.v2beta1.ExtraHeader extra_headers = 9 [json_name = "extraHeaders"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtraHeaders()
    {
        return $this->extra_headers;
    }

    /**
     * Extra headers to send to the trunk
     *
     * Generated from protobuf field <code>repeated .fonoster.routr.connect.numbers.v2beta1.ExtraHeader extra_headers = 9 [json_name = "extraHeaders"];</code>
     *
     * @param  array<\Fonoster\Routr\Connect\Numbers\V2beta1\ExtraHeader>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtraHeaders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fonoster\Routr\Connect\Numbers\V2beta1\ExtraHeader::class);
        $this->extra_headers = $arr;

        return $this;
    }

    /**
     * Reference to the trunk this number is associated with
     *
     * Generated from protobuf field <code>string trunk_ref = 10 [json_name = "trunkRef"];</code>
     *
     * @return string
     */
    public function getTrunkRef()
    {
        return $this->trunk_ref;
    }

    /**
     * Reference to the trunk this number is associated with
     *
     * Generated from protobuf field <code>string trunk_ref = 10 [json_name = "trunkRef"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setTrunkRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->trunk_ref = $var;

        return $this;
    }

    /**
     * The extended attributes of the Number
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 11 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the Number
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 11 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
