<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/acl.proto

namespace Fonoster\Routr\Connect\Acl\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Struct;

/**
 * The message for AccessControlList resource
 *
 * Generated from protobuf message <code>fonoster.routr.connect.acl.v2beta1.AccessControlList</code>
 */
class AccessControlList extends \Google\Protobuf\Internal\Message
{
    /**
     * The version of the API
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     */
    protected $api_version = '';
    /**
     * The ACL reference
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     */
    protected $ref = '';
    /**
     * A friendly name for the ACL
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The list of allowed IP addresses
     *
     * Generated from protobuf field <code>repeated string allow = 4 [json_name = "allow"];</code>
     */
    private $allow;
    /**
     * The list of denied IP addresses
     *
     * Generated from protobuf field <code>repeated string deny = 5 [json_name = "deny"];</code>
     */
    private $deny;
    /**
     * The date the ACL was created
     *
     * Generated from protobuf field <code>int32 created_at = 6 [json_name = "createdAt"];</code>
     */
    protected $created_at = 0;
    /**
     * The date the ACL was last updated
     *
     * Generated from protobuf field <code>int32 updated_at = 7 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = 0;
    /**
     * The extended attributes of the ACL
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 8 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string $api_version
     *           The version of the API
     * @type string $ref
     *           The ACL reference
     * @type string $name
     *           A friendly name for the ACL
     * @type array<string>|\Google\Protobuf\Internal\RepeatedField $allow
     *           The list of allowed IP addresses
     * @type array<string>|\Google\Protobuf\Internal\RepeatedField $deny
     *           The list of denied IP addresses
     * @type int $created_at
     *           The date the ACL was created
     * @type int $updated_at
     *           The date the ACL was last updated
     * @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the ACL
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Acl::initOnce();
        parent::__construct($data);
    }

    /**
     * The version of the API
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @return string
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * The version of the API
     *
     * Generated from protobuf field <code>string api_version = 1 [json_name = "apiVersion"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setApiVersion($var)
    {
        GPBUtil::checkString($var, true);
        $this->api_version = $var;

        return $this;
    }

    /**
     * The ACL reference
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * The ACL reference
     *
     * Generated from protobuf field <code>string ref = 2 [json_name = "ref"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setRef($var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * A friendly name for the ACL
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * A friendly name for the ACL
     *
     * Generated from protobuf field <code>string name = 3 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The list of allowed IP addresses
     *
     * Generated from protobuf field <code>repeated string allow = 4 [json_name = "allow"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllow()
    {
        return $this->allow;
    }

    /**
     * The list of allowed IP addresses
     *
     * Generated from protobuf field <code>repeated string allow = 4 [json_name = "allow"];</code>
     *
     * @param  array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllow($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->allow = $arr;

        return $this;
    }

    /**
     * The list of denied IP addresses
     *
     * Generated from protobuf field <code>repeated string deny = 5 [json_name = "deny"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeny()
    {
        return $this->deny;
    }

    /**
     * The list of denied IP addresses
     *
     * Generated from protobuf field <code>repeated string deny = 5 [json_name = "deny"];</code>
     *
     * @param  array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeny($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->deny = $arr;

        return $this;
    }

    /**
     * The date the ACL was created
     *
     * Generated from protobuf field <code>int32 created_at = 6 [json_name = "createdAt"];</code>
     *
     * @return integer
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * The date the ACL was created
     *
     * Generated from protobuf field <code>int32 created_at = 6 [json_name = "createdAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * The date the ACL was last updated
     *
     * Generated from protobuf field <code>int32 updated_at = 7 [json_name = "updatedAt"];</code>
     *
     * @return integer
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * The date the ACL was last updated
     *
     * Generated from protobuf field <code>int32 updated_at = 7 [json_name = "updatedAt"];</code>
     *
     * @param  integer $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt32($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * The extended attributes of the ACL
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 8 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the ACL
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 8 [json_name = "extended"];</code>
     *
     * @param  Struct $var
     * @return $this
     * @throws \Exception
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
