<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/acl.proto

namespace Fonoster\Routr\Connect\Acl\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for the AccessControlList.Create method
 *
 * Generated from protobuf message <code>fonoster.routr.connect.acl.v2beta1.CreateACLRequest</code>
 */
class CreateACLRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * A friendly name for the ACL
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The list of allowed IP addresses
     *
     * Generated from protobuf field <code>repeated string allow = 3 [json_name = "allow"];</code>
     */
    private $allow;
    /**
     * The list of denied IP addresses
     *
     * Generated from protobuf field <code>repeated string deny = 4 [json_name = "deny"];</code>
     */
    private $deny;
    /**
     * The extended attributes of the ACL
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 5 [json_name = "extended"];</code>
     */
    protected $extended = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           A friendly name for the ACL
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $allow
     *           The list of allowed IP addresses
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $deny
     *           The list of denied IP addresses
     *     @type \Google\Protobuf\Struct $extended
     *           The extended attributes of the ACL
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Proto\Acl::initOnce();
        parent::__construct($data);
    }

    /**
     * A friendly name for the ACL
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * A friendly name for the ACL
     *
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The list of allowed IP addresses
     *
     * Generated from protobuf field <code>repeated string allow = 3 [json_name = "allow"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllow()
    {
        return $this->allow;
    }

    /**
     * The list of allowed IP addresses
     *
     * Generated from protobuf field <code>repeated string allow = 3 [json_name = "allow"];</code>
     *
     * @param  array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllow($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->allow = $arr;

        return $this;
    }

    /**
     * The list of denied IP addresses
     *
     * Generated from protobuf field <code>repeated string deny = 4 [json_name = "deny"];</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeny()
    {
        return $this->deny;
    }

    /**
     * The list of denied IP addresses
     *
     * Generated from protobuf field <code>repeated string deny = 4 [json_name = "deny"];</code>
     *
     * @param  array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeny($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->deny = $arr;

        return $this;
    }

    /**
     * The extended attributes of the ACL
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 5 [json_name = "extended"];</code>
     *
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtended()
    {
        return $this->extended;
    }

    public function hasExtended()
    {
        return isset($this->extended);
    }

    public function clearExtended()
    {
        unset($this->extended);
    }

    /**
     * The extended attributes of the ACL
     *
     * Generated from protobuf field <code>.google.protobuf.Struct extended = 5 [json_name = "extended"];</code>
     *
     * @param  \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtended($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extended = $var;

        return $this;
    }
}
